In [2]:
import numpy as np
import pandas as pd
import os
notebook_path = os.path.abspath('Data_cleanup.ipynb')
directory = os.path.dirname(notebook_path)

In [2]:
# v1 start
# Cleaning of the vaccination data from 
# https://data.cdc.gov/Vaccinations/COVID-19-Vaccinations-in-the-United-States-Jurisdi/unsk-b7fc/data
data_path = os.path.join(directory, 'COVID-19_Vaccinations_in_the_United_States_Jurisdiction.csv')
df = pd.read_csv(data_path)

In [8]:
df_clean_v1 = df.loc[:,['Date', 'Location', 'Distributed', 'Administered', 'Administered_Dose1_Pop_Pct', 'Series_Complete_Pop_Pct', 'Additional_Doses_Vax_Pct']]

In [11]:
data_v1_path = os.path.join(directory, 'data_clean_v1.csv')
df_clean_v1.to_csv(data_v1_path, index=False)
# v1 end

In [79]:
# v2 add sentiment start
# Adding proper state markings to CSV of tweets including sentiment
data_path = os.path.join(directory, 'full_data_withSentiment.csv')
df = pd.read_csv(data_path)
print(df)

        Unnamed: 0  Unnamed: 0.1             tweet_id  \
0                0             0  1344871462692384768
1                1             1  1344871464340774917
2                2             2  1344871810815426561
3                3             3  1344871877819379712
4                4             4  1344871963894931461
...            ...           ...                  ...
539826      646992        646992  1594173500578680832
539827      646993        646993  1594173595793514496
539828      646994        646994  1594185319439474688
539829      646995        646995  1594185386326167552
539830      646996        646996  1594188564954492928

                                                     text            loc_id  \
0       Feliz a√±o nuevo 2021 ojal√° y que el maldito co...  4ec01c9dbc693497
1                         Coronavirus is over now. Right?  0019267176557307
2       Da village is popping off we are now open good...  009103ea59aa47b3
3         RIP coronavirus\n\n2020-2020.\n\nRest in Piss‚ù§Ô∏è  74316979ec360e9f
4       Coronavirus is officially expired!ü§£ #HappyNewY...  25d42ee1dd69564c
...                                                   ...               ...
539826           @RonnyJacksonTX https://t.co/szZsZI6Ug0.  1d9a5370a355ab0c
539827          @RonnyJacksonTX https://t.co/szZsZI6Ug0 ü§î  1d9a5370a355ab0c
539828  @GovMurphy Read something. Take 20 seconds.  W...  01e587be3cdfd4f3
539829  @MerMom123 @KevinSixx13 @MarshaBlackburn A Pen...  6a83705c6ef0b6b0
539830  Sick since Wednesday #COVID19 no one masks in ...  71d65c0e6d94efab

                       created_at  retweet_count  reply_count  likes_count  \
0       2021-01-01 05:01:57+00:00              0            0            1
1       2021-01-01 05:01:58+00:00              0            1            0
2       2021-01-01 05:03:20+00:00              0            0            1
3       2021-01-01 05:03:36+00:00              0            0            2
4       2021-01-01 05:03:57+00:00              1            0            1
...                           ...            ...          ...          ...
539826  2022-11-20 03:39:15+00:00              0            0            0
539827  2022-11-20 03:39:38+00:00              0            0            0
539828  2022-11-20 04:26:13+00:00              0            0            0
539829  2022-11-20 04:26:29+00:00              0            1            5
539830  2022-11-20 04:39:07+00:00              1            0            0

        quote_count  ...  lang is_sensitive  \
0                 0  ...    es        False
1                 0  ...    en        False
2                 0  ...    en        False
3                 0  ...    en        False
4                 0  ...    en        False
...             ...  ...   ...          ...
539826            0  ...   qme        False
539827            0  ...   und        False
539828            0  ...    en        False
539829            0  ...    en        False
539830            0  ...    en        False

                                                    bbox         loc_name  \
0         [-87.634643, 24.396308, -79.974307, 31.001056]          Florida
1       [-84.4832977, 39.2957423, -84.346523, 39.374689]     West Chester
2          [-81.54525, 40.872987, -81.416329, 40.997434]            Green
3         [-82.928586, 42.450585, -82.859921, 42.541054]  St Clair Shores
4         [-76.892963, 42.358696, -76.856492, 42.399302]     Watkins Glen
...                                                  ...              ...
539826   [-87.940033, 41.644102, -87.523993, 42.0230669]          Chicago
539827   [-87.940033, 41.644102, -87.523993, 42.0230669]          Chicago
539828  [-121.932378, 36.540748, -121.912765, 36.564516]           Carmel
539829  [-77.248462, 38.971077, -77.1418208, 39.0693022]          Potomac
539830  [-109.050173, 31.332176, -103.002065, 37.000294]       New Mexico

       loc_type            loc_fname    neg    neu    pos  compound
0         admin         Florida, USA  0.000  1.000  0.000    0.0000
1          city     West Chester, OH  0.000  1.000  0.000    0.0000
2          city            Green, OH  0.241  0.468  0.291    0.1280
3          city  St Clair Shores, MI  0.000  1.000  0.000    0.0000
4          city     Watkins Glen, NY  0.000  1.000  0.000    0.0000
...         ...                  ...    ...    ...    ...       ...
539826     city          Chicago, IL  0.000  1.000  0.000    0.0000
539827     city          Chicago, IL  0.000  1.000  0.000    0.0000
539828     city           Carmel, CA  0.192  0.808  0.000   -0.6124
539829     city          Potomac, MD  0.056  0.801  0.143    0.5030
539830    admin      New Mexico, USA  0.333  0.667  0.000   -0.6705

[539831 rows x 22 columns]

In [75]:
us_state_to_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "U.S. Virgin Islands": "VI",
    "Virgin Islands" : "VI",
    "WILMINGTON" : "NC",
    "PHILADELPHIA" : "PA",
    "MOBILE-PENSACOLA (FT WALT)" : "FL",
    "HOUSTON" : "TX",
    "NEW YORK" : "NY",
    "MINNEAPOLIS-ST. PAUL" : "MN", 
    "FRESNO-VISALIA" : "CA",
    "DETROIT" : "MI",
    "ALBANY-SCHENECTADY-TROY": "NY",
    "BOSTON (MANCHESTER)" : "NH",
    "MADISON" : "WI",
    "JACKSON" : "MS",
    "AUSTIN" : "TX",
    "SHERMAN-ADA" : "TX",
    "NASHVILLE" : "TN",
    "LOS ANGELES" : "CA",
    "LA CROSSE-EAU CLAIRE" : "WI",
    "TWIN FALLS" : "ID",
    "CHARLESTON" : "SC",
    "ATLANTA" : "GA",
    "HARLINGEN-WSLCO-BRNSVL-MCA" : "TX",
    "TALLAHASSEE-THOMASVILLE" : "FL",
    
}

In [24]:
# print(us_state_to_abbrev[df['loc_fname'][0].split(',')[0]].strip())
# print(df['loc_fname'][1].split(',')[1].strip())
def what_state(row):
    if row['loc_type'] == 'admin':
        return us_state_to_abbrev[row['loc_fname'].split(',')[0]].strip()
    elif row['loc_type'] == 'city':
        return row['loc_fname'].split(',')[1].strip()
    else:
        return None

FL
OH

In [80]:
df['state'] = df.apply(lambda row: what_state(row), axis=1)
print(df)

        Unnamed: 0  Unnamed: 0.1             tweet_id  \
0                0             0  1344871462692384768
1                1             1  1344871464340774917
2                2             2  1344871810815426561
3                3             3  1344871877819379712
4                4             4  1344871963894931461
...            ...           ...                  ...
539826      646992        646992  1594173500578680832
539827      646993        646993  1594173595793514496
539828      646994        646994  1594185319439474688
539829      646995        646995  1594185386326167552
539830      646996        646996  1594188564954492928

                                                     text            loc_id  \
0       Feliz a√±o nuevo 2021 ojal√° y que el maldito co...  4ec01c9dbc693497
1                         Coronavirus is over now. Right?  0019267176557307
2       Da village is popping off we are now open good...  009103ea59aa47b3
3         RIP coronavirus\n\n2020-2020.\n\nRest in Piss‚ù§Ô∏è  74316979ec360e9f
4       Coronavirus is officially expired!ü§£ #HappyNewY...  25d42ee1dd69564c
...                                                   ...               ...
539826           @RonnyJacksonTX https://t.co/szZsZI6Ug0.  1d9a5370a355ab0c
539827          @RonnyJacksonTX https://t.co/szZsZI6Ug0 ü§î  1d9a5370a355ab0c
539828  @GovMurphy Read something. Take 20 seconds.  W...  01e587be3cdfd4f3
539829  @MerMom123 @KevinSixx13 @MarshaBlackburn A Pen...  6a83705c6ef0b6b0
539830  Sick since Wednesday #COVID19 no one masks in ...  71d65c0e6d94efab

                       created_at  retweet_count  reply_count  likes_count  \
0       2021-01-01 05:01:57+00:00              0            0            1
1       2021-01-01 05:01:58+00:00              0            1            0
2       2021-01-01 05:03:20+00:00              0            0            1
3       2021-01-01 05:03:36+00:00              0            0            2
4       2021-01-01 05:03:57+00:00              1            0            1
...                           ...            ...          ...          ...
539826  2022-11-20 03:39:15+00:00              0            0            0
539827  2022-11-20 03:39:38+00:00              0            0            0
539828  2022-11-20 04:26:13+00:00              0            0            0
539829  2022-11-20 04:26:29+00:00              0            1            5
539830  2022-11-20 04:39:07+00:00              1            0            0

        quote_count  ...  is_sensitive  \
0                 0  ...         False
1                 0  ...         False
2                 0  ...         False
3                 0  ...         False
4                 0  ...         False
...             ...  ...           ...
539826            0  ...         False
539827            0  ...         False
539828            0  ...         False
539829            0  ...         False
539830            0  ...         False

                                                    bbox         loc_name  \
0         [-87.634643, 24.396308, -79.974307, 31.001056]          Florida
1       [-84.4832977, 39.2957423, -84.346523, 39.374689]     West Chester
2          [-81.54525, 40.872987, -81.416329, 40.997434]            Green
3         [-82.928586, 42.450585, -82.859921, 42.541054]  St Clair Shores
4         [-76.892963, 42.358696, -76.856492, 42.399302]     Watkins Glen
...                                                  ...              ...
539826   [-87.940033, 41.644102, -87.523993, 42.0230669]          Chicago
539827   [-87.940033, 41.644102, -87.523993, 42.0230669]          Chicago
539828  [-121.932378, 36.540748, -121.912765, 36.564516]           Carmel
539829  [-77.248462, 38.971077, -77.1418208, 39.0693022]          Potomac
539830  [-109.050173, 31.332176, -103.002065, 37.000294]       New Mexico

        loc_type            loc_fname    neg    neu    pos  compound  state
0          admin         Florida, USA  0.000  1.000  0.000    0.0000     FL
1           city     West Chester, OH  0.000  1.000  0.000    0.0000     OH
2           city            Green, OH  0.241  0.468  0.291    0.1280     OH
3           city  St Clair Shores, MI  0.000  1.000  0.000    0.0000     MI
4           city     Watkins Glen, NY  0.000  1.000  0.000    0.0000     NY
...          ...                  ...    ...    ...    ...       ...    ...
539826      city          Chicago, IL  0.000  1.000  0.000    0.0000     IL
539827      city          Chicago, IL  0.000  1.000  0.000    0.0000     IL
539828      city           Carmel, CA  0.192  0.808  0.000   -0.6124     CA
539829      city          Potomac, MD  0.056  0.801  0.143    0.5030     MD
539830     admin      New Mexico, USA  0.333  0.667  0.000   -0.6705     NM

[539831 rows x 23 columns]

In [81]:
df2 = df[df.loc_type != "poi"]
print(df2)

        Unnamed: 0  Unnamed: 0.1             tweet_id  \
0                0             0  1344871462692384768
1                1             1  1344871464340774917
2                2             2  1344871810815426561
3                3             3  1344871877819379712
4                4             4  1344871963894931461
...            ...           ...                  ...
539826      646992        646992  1594173500578680832
539827      646993        646993  1594173595793514496
539828      646994        646994  1594185319439474688
539829      646995        646995  1594185386326167552
539830      646996        646996  1594188564954492928

                                                     text            loc_id  \
0       Feliz a√±o nuevo 2021 ojal√° y que el maldito co...  4ec01c9dbc693497
1                         Coronavirus is over now. Right?  0019267176557307
2       Da village is popping off we are now open good...  009103ea59aa47b3
3         RIP coronavirus\n\n2020-2020.\n\nRest in Piss‚ù§Ô∏è  74316979ec360e9f
4       Coronavirus is officially expired!ü§£ #HappyNewY...  25d42ee1dd69564c
...                                                   ...               ...
539826           @RonnyJacksonTX https://t.co/szZsZI6Ug0.  1d9a5370a355ab0c
539827          @RonnyJacksonTX https://t.co/szZsZI6Ug0 ü§î  1d9a5370a355ab0c
539828  @GovMurphy Read something. Take 20 seconds.  W...  01e587be3cdfd4f3
539829  @MerMom123 @KevinSixx13 @MarshaBlackburn A Pen...  6a83705c6ef0b6b0
539830  Sick since Wednesday #COVID19 no one masks in ...  71d65c0e6d94efab

                       created_at  retweet_count  reply_count  likes_count  \
0       2021-01-01 05:01:57+00:00              0            0            1
1       2021-01-01 05:01:58+00:00              0            1            0
2       2021-01-01 05:03:20+00:00              0            0            1
3       2021-01-01 05:03:36+00:00              0            0            2
4       2021-01-01 05:03:57+00:00              1            0            1
...                           ...            ...          ...          ...
539826  2022-11-20 03:39:15+00:00              0            0            0
539827  2022-11-20 03:39:38+00:00              0            0            0
539828  2022-11-20 04:26:13+00:00              0            0            0
539829  2022-11-20 04:26:29+00:00              0            1            5
539830  2022-11-20 04:39:07+00:00              1            0            0

        quote_count  ...  is_sensitive  \
0                 0  ...         False
1                 0  ...         False
2                 0  ...         False
3                 0  ...         False
4                 0  ...         False
...             ...  ...           ...
539826            0  ...         False
539827            0  ...         False
539828            0  ...         False
539829            0  ...         False
539830            0  ...         False

                                                    bbox         loc_name  \
0         [-87.634643, 24.396308, -79.974307, 31.001056]          Florida
1       [-84.4832977, 39.2957423, -84.346523, 39.374689]     West Chester
2          [-81.54525, 40.872987, -81.416329, 40.997434]            Green
3         [-82.928586, 42.450585, -82.859921, 42.541054]  St Clair Shores
4         [-76.892963, 42.358696, -76.856492, 42.399302]     Watkins Glen
...                                                  ...              ...
539826   [-87.940033, 41.644102, -87.523993, 42.0230669]          Chicago
539827   [-87.940033, 41.644102, -87.523993, 42.0230669]          Chicago
539828  [-121.932378, 36.540748, -121.912765, 36.564516]           Carmel
539829  [-77.248462, 38.971077, -77.1418208, 39.0693022]          Potomac
539830  [-109.050173, 31.332176, -103.002065, 37.000294]       New Mexico

        loc_type            loc_fname    neg    neu    pos  compound  state
0          admin         Florida, USA  0.000  1.000  0.000    0.0000     FL
1           city     West Chester, OH  0.000  1.000  0.000    0.0000     OH
2           city            Green, OH  0.241  0.468  0.291    0.1280     OH
3           city  St Clair Shores, MI  0.000  1.000  0.000    0.0000     MI
4           city     Watkins Glen, NY  0.000  1.000  0.000    0.0000     NY
...          ...                  ...    ...    ...    ...       ...    ...
539826      city          Chicago, IL  0.000  1.000  0.000    0.0000     IL
539827      city          Chicago, IL  0.000  1.000  0.000    0.0000     IL
539828      city           Carmel, CA  0.192  0.808  0.000   -0.6124     CA
539829      city          Potomac, MD  0.056  0.801  0.143    0.5030     MD
539830     admin      New Mexico, USA  0.333  0.667  0.000   -0.6705     NM

[528914 rows x 23 columns]

In [82]:
data_v2_path = os.path.join(directory, 'data_clean_v2.csv')
df2.to_csv(data_v2_path, index=False)
# v2 end

In [11]:
#v3 start
#Combining batches from emotional analysis of the tweets
df_batches = []
batches_path = os.path.join(directory, 'emotion_batches')
for batch in os.listdir(batches_path):
    df_batches.append(pd.read_csv(os.path.join(batches_path, batch)))
# print(df_batches)

In [12]:
combined_df = pd.concat(df_batches, axis=0, ignore_index=True)

        Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1             tweet_id  \
0                0             0             0.0  1344871462692384768
1                1             1             1.0  1344871464340774917
2                2             2             2.0  1344871810815426561
3                3             3             3.0  1344871877819379712
4                4             4             4.0  1344871963894931461
...            ...           ...             ...                  ...
528909       99995        123564        123564.0  1363545855479980034
528910       99996        123565        123565.0  1363545992759549953
528911       99997        123566        123566.0  1363546487834238977
528912       99998        123567        123567.0  1363546510416306181
528913       99999        123568        123568.0  1363546537113051138

                                                     text            loc_id  \
0       Feliz a√±o nuevo 2021 ojal√° y que el maldito co...  4ec01c9dbc693497
1                         Coronavirus is over now. Right?  0019267176557307
2       Da village is popping off we are now open good...  009103ea59aa47b3
3         RIP coronavirus\n\n2020-2020.\n\nRest in Piss‚ù§Ô∏è  74316979ec360e9f
4       Coronavirus is officially expired!ü§£ #HappyNewY...  25d42ee1dd69564c
...                                                   ...               ...
528909  Great questions by @margbrennan .. I think we ...  01a9a39529b27f36
528910  So grateful for @vhcschools and the work done ...  7117a74ec1bd6dc5
528911  Public health messaging has meaning: With the ...  7142eb97ae21e839
528912  But there are signs of hope which is the first...  7142eb97ae21e839
528913  However #COVID19 dissonance is now reduced, th...  7142eb97ae21e839

                       created_at  retweet_count  reply_count  likes_count  \
0       2021-01-01 05:01:57+00:00              0            0            1
1       2021-01-01 05:01:58+00:00              0            1            0
2       2021-01-01 05:03:20+00:00              0            0            1
3       2021-01-01 05:03:36+00:00              0            0            2
4       2021-01-01 05:03:57+00:00              1            0            1
...                           ...            ...          ...          ...
528909  2021-02-21 17:47:20+00:00              0            0            0
528910  2021-02-21 17:47:52+00:00              2            0           16
528911  2021-02-21 17:49:50+00:00              1            1            1
528912  2021-02-21 17:49:56+00:00              0            1            0
528913  2021-02-21 17:50:02+00:00              0            0            1

        ...    neu    pos compound state  emotion Happy Angry Surprise   Sad  \
0       ...  1.000  0.000   0.0000    FL    error   0.0   0.0      0.0  0.00
1       ...  1.000  0.000   0.0000    OH    error   0.0   0.0      0.0  0.00
2       ...  0.468  0.291   0.1280    OH    error   0.0   0.0      0.0  0.00
3       ...  1.000  0.000   0.0000    MI    error   0.0   0.0      0.0  0.00
4       ...  1.000  0.000   0.0000    NY    error   0.0   0.0      0.0  0.00
...     ...    ...    ...      ...   ...      ...   ...   ...      ...   ...
528909  ...  0.795  0.205   0.6597    NY      NaN   0.5   0.0      0.0  0.00
528910  ...  0.826  0.174   0.5551    AL      NaN   0.5   0.0      0.0  0.00
528911  ...  1.000  0.000   0.0000    GA      NaN   0.0   0.0      1.0  0.00
528912  ...  0.903  0.097   0.5927    GA      NaN   0.0   0.0      0.0  0.00
528913  ...  0.814  0.069  -0.2449    GA      NaN   0.0   0.0      0.0  0.25

        Fear
0       0.00
1       0.00
2       1.00
3       0.00
4       0.00
...      ...
528909  0.50
528910  0.50
528911  0.00
528912  1.00
528913  0.75

[528914 rows x 30 columns]

In [19]:
combined_df = combined_df.drop(['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1', 'emotion'], axis=1)

                   tweet_id  \
0       1344871462692384768
1       1344871464340774917
2       1344871810815426561
3       1344871877819379712
4       1344871963894931461
...                     ...
528909  1363545855479980034
528910  1363545992759549953
528911  1363546487834238977
528912  1363546510416306181
528913  1363546537113051138

                                                     text            loc_id  \
0       Feliz a√±o nuevo 2021 ojal√° y que el maldito co...  4ec01c9dbc693497
1                         Coronavirus is over now. Right?  0019267176557307
2       Da village is popping off we are now open good...  009103ea59aa47b3
3         RIP coronavirus\n\n2020-2020.\n\nRest in Piss‚ù§Ô∏è  74316979ec360e9f
4       Coronavirus is officially expired!ü§£ #HappyNewY...  25d42ee1dd69564c
...                                                   ...               ...
528909  Great questions by @margbrennan .. I think we ...  01a9a39529b27f36
528910  So grateful for @vhcschools and the work done ...  7117a74ec1bd6dc5
528911  Public health messaging has meaning: With the ...  7142eb97ae21e839
528912  But there are signs of hope which is the first...  7142eb97ae21e839
528913  However #COVID19 dissonance is now reduced, th...  7142eb97ae21e839

                       created_at  retweet_count  reply_count  likes_count  \
0       2021-01-01 05:01:57+00:00              0            0            1
1       2021-01-01 05:01:58+00:00              0            1            0
2       2021-01-01 05:03:20+00:00              0            0            1
3       2021-01-01 05:03:36+00:00              0            0            2
4       2021-01-01 05:03:57+00:00              1            0            1
...                           ...            ...          ...          ...
528909  2021-02-21 17:47:20+00:00              0            0            0
528910  2021-02-21 17:47:52+00:00              2            0           16
528911  2021-02-21 17:49:50+00:00              1            1            1
528912  2021-02-21 17:49:56+00:00              0            1            0
528913  2021-02-21 17:50:02+00:00              0            0            1

        quote_count            author_id               source  ...    neg  \
0                 0            195956535  Twitter for Android  ...  0.000
1                 0           2434470627   Twitter for iPhone  ...  0.000
2                 0  1220353801539870721   Twitter for iPhone  ...  0.241
3                 0            531818639   Twitter for iPhone  ...  0.000
4                 0           1297298982  Twitter for Android  ...  0.000
...             ...                  ...                  ...  ...    ...
528909            0             24569259   Twitter for iPhone  ...  0.000
528910            0            477317690   Twitter for iPhone  ...  0.000
528911            0             18679867   Twitter for iPhone  ...  0.000
528912            0             18679867   Twitter for iPhone  ...  0.000
528913            0             18679867   Twitter for iPhone  ...  0.117

          neu    pos compound state Happy  Angry  Surprise   Sad  Fear
0       1.000  0.000   0.0000    FL   0.0    0.0       0.0  0.00  0.00
1       1.000  0.000   0.0000    OH   0.0    0.0       0.0  0.00  0.00
2       0.468  0.291   0.1280    OH   0.0    0.0       0.0  0.00  1.00
3       1.000  0.000   0.0000    MI   0.0    0.0       0.0  0.00  0.00
4       1.000  0.000   0.0000    NY   0.0    0.0       0.0  0.00  0.00
...       ...    ...      ...   ...   ...    ...       ...   ...   ...
528909  0.795  0.205   0.6597    NY   0.5    0.0       0.0  0.00  0.50
528910  0.826  0.174   0.5551    AL   0.5    0.0       0.0  0.00  0.50
528911  1.000  0.000   0.0000    GA   0.0    0.0       1.0  0.00  0.00
528912  0.903  0.097   0.5927    GA   0.0    0.0       0.0  0.00  1.00
528913  0.814  0.069  -0.2449    GA   0.0    0.0       0.0  0.25  0.75

[528914 rows x 26 columns]

In [82]:
df_v3_path = os.path.join(directory, 'data_with_sentiment_and_emotion.csv')
combined_df.to_csv(df_v3_path, index=False)
#v3 end

In [253]:
#v4 start
#Generating CSVs of average values of sentiment and emotion by week and month
data_v1_path = os.path.join(directory, 'data_clean_v1.csv')
df_v3_path = os.path.join(directory, 'data_with_sentiment_and_emotion.csv')
vax_data = pd.read_csv(data_v1_path)
vax_data['Date'] = pd.to_datetime(vax_data['Date'])
vax_data['Year'] = vax_data['Date'].dt.year
vax_data['Month'] = vax_data['Date'].dt.month
vax_data['Week'] = vax_data['Date'].dt.week
vax_data.rename(columns={'Location':'state'}, inplace=True)
# print(vax_data)
combined_df = pd.read_csv(df_v3_path)
combined_df['Date'] = pd.to_datetime(combined_df['created_at'])
combined_df['Year'] = combined_df['Date'].dt.year
combined_df['Month'] = combined_df['Date'].dt.month
combined_df['Week'] = combined_df['Date'].dt.week
combined_df.to_csv(df_v3_path, index=False)
# print(combined_df)

E:\miniconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.

E:\miniconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:15: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  from ipykernel import kernelapp as app

In [254]:
vax_path = os.path.join(directory, 'vax_data_clean.csv')
vax_data.to_csv(vax_path, index=False)

In [255]:
vax_by_month = vax_data.groupby(['state', 'Year', 'Month'])
vax_by_month = vax_by_month.mean()[['Administered_Dose1_Pop_Pct', 'Series_Complete_Pop_Pct', 'Additional_Doses_Vax_Pct']].reset_index()
print(vax_by_month)

     state  Year  Month  Administered_Dose1_Pop_Pct  Series_Complete_Pop_Pct  \
0       AK  2020     12                    0.000000                 0.000000
1       AK  2021      1                    0.000000                 0.000000
2       AK  2021      2                   11.389286                 0.000000
3       AK  2021      3                   28.477419                16.345161
4       AK  2021      4                   38.423333                29.693333
...    ...   ...    ...                         ...                      ...
1543    WY  2022      7                   58.850000                51.500000
1544    WY  2022      8                   59.100000                51.780000
1545    WY  2022      9                   59.375000                51.975000
1546    WY  2022     10                   59.750000                52.275000
1547    WY  2022     11                   60.300000                52.650000

      Additional_Doses_Vax_Pct
0                        0.000
1                        0.000
2                        0.000
3                        0.000
4                        0.000
...                        ...
1543                    44.725
1544                    45.100
1545                    45.350
1546                    45.825
1547                    46.475

[1548 rows x 6 columns]

In [256]:
tweet_vals_by_month = combined_df.groupby(['state', 'Year', 'Month'])
tweet_vals_by_month = tweet_vals_by_month.mean()[['neg', 'neu', 'pos', 'compound', 'Happy', 'Angry', 'Surprise', 'Sad', 'Fear']].reset_index()
print(tweet_vals_by_month)

     state  Year  Month       neg       neu       pos  compound     Happy  \
0       AK  2021      1  0.087685  0.836387  0.075910  0.014579  0.096036
1       AK  2021      2  0.067141  0.837577  0.095310  0.093146  0.095493
2       AK  2021      3  0.059053  0.852653  0.088307  0.081089  0.104267
3       AK  2021      4  0.075697  0.790273  0.134030  0.135488  0.279394
4       AK  2021      5  0.066161  0.821613  0.112226  0.069274  0.032258
...    ...   ...    ...       ...       ...       ...       ...       ...
1224    WY  2022      7  0.038333  0.910833  0.050833 -0.052350  0.238333
1225    WY  2022      8  0.000000  1.000000  0.000000  0.000000  0.000000
1226    WY  2022      9  0.144500  0.599500  0.256500  0.031400  0.000000
1227    WY  2022     10  0.179833  0.717333  0.103000 -0.162017  0.000000
1228    WY  2022     11  0.041000  0.871500  0.087500  0.180600  0.000000

         Angry  Surprise       Sad      Fear
0     0.050901  0.103153  0.132432  0.283784
1     0.040845  0.106620  0.144225  0.204085
2     0.020933  0.136267  0.138133  0.253467
3     0.059697  0.076667  0.190606  0.180909
4     0.059032  0.139677  0.197742  0.280645
...        ...       ...       ...       ...
1224  0.166667  0.000000  0.023333  0.071667
1225  0.000000  0.000000  0.000000  0.000000
1226  0.335000  0.330000  0.000000  0.335000
1227  0.138333  0.291667  0.083333  0.486667
1228  0.000000  0.000000  1.000000  0.000000

[1229 rows x 12 columns]

In [257]:
df_by_month = tweet_vals_by_month.merge(vax_by_month, how='inner', on=['state', 'Year', 'Month'])
print(df_by_month)
path = os.path.join(directory, 'monthly_vax_sentiment_emotion.csv')
df_by_month.to_csv(path, index=False)

     state  Year  Month       neg       neu       pos  compound     Happy  \
0       AK  2021      1  0.087685  0.836387  0.075910  0.014579  0.096036
1       AK  2021      2  0.067141  0.837577  0.095310  0.093146  0.095493
2       AK  2021      3  0.059053  0.852653  0.088307  0.081089  0.104267
3       AK  2021      4  0.075697  0.790273  0.134030  0.135488  0.279394
4       AK  2021      5  0.066161  0.821613  0.112226  0.069274  0.032258
...    ...   ...    ...       ...       ...       ...       ...       ...
1174    WY  2022      7  0.038333  0.910833  0.050833 -0.052350  0.238333
1175    WY  2022      8  0.000000  1.000000  0.000000  0.000000  0.000000
1176    WY  2022      9  0.144500  0.599500  0.256500  0.031400  0.000000
1177    WY  2022     10  0.179833  0.717333  0.103000 -0.162017  0.000000
1178    WY  2022     11  0.041000  0.871500  0.087500  0.180600  0.000000

         Angry  Surprise       Sad      Fear  Administered_Dose1_Pop_Pct  \
0     0.050901  0.103153  0.132432  0.283784                    0.000000
1     0.040845  0.106620  0.144225  0.204085                   11.389286
2     0.020933  0.136267  0.138133  0.253467                   28.477419
3     0.059697  0.076667  0.190606  0.180909                   38.423333
4     0.059032  0.139677  0.197742  0.280645                   43.925806
...        ...       ...       ...       ...                         ...
1174  0.166667  0.000000  0.023333  0.071667                   58.850000
1175  0.000000  0.000000  0.000000  0.000000                   59.100000
1176  0.335000  0.330000  0.000000  0.335000                   59.375000
1177  0.138333  0.291667  0.083333  0.486667                   59.750000
1178  0.000000  0.000000  1.000000  0.000000                   60.300000

      Series_Complete_Pop_Pct  Additional_Doses_Vax_Pct
0                    0.000000                     0.000
1                    0.000000                     0.000
2                   16.345161                     0.000
3                   29.693333                     0.000
4                   37.661290                     0.000
...                       ...                       ...
1174                51.500000                    44.725
1175                51.780000                    45.100
1176                51.975000                    45.350
1177                52.275000                    45.825
1178                52.650000                    46.475

[1179 rows x 15 columns]

In [258]:
vax_by_week = vax_data.groupby(['state', 'Year', 'Month', 'Week'])
vax_by_week = vax_by_week.mean()[['Administered_Dose1_Pop_Pct', 'Series_Complete_Pop_Pct', 'Additional_Doses_Vax_Pct']].reset_index()
tweet_vals_by_week = combined_df.groupby(['state', 'Year', 'Month', 'Week'])
tweet_vals_by_week = tweet_vals_by_week.mean()[['neg', 'neu', 'pos', 'compound', 'Happy', 'Angry', 'Surprise', 'Sad', 'Fear']].reset_index()
df_by_week = tweet_vals_by_week.merge(vax_by_week, how='inner', on=['state', 'Year', 'Month', 'Week'])
print(df_by_week)
path = os.path.join(directory, 'weekly_vax_sentiment_emotion.csv')
df_by_week.to_csv(path, index=False)
#v4 end

     state  Year  Month  Week       neg       neu       pos  compound  \
0       AK  2021      1     1  0.080263  0.872000  0.047737 -0.049653
1       AK  2021      1     2  0.070125  0.855656  0.074187  0.025209
2       AK  2021      1     3  0.067444  0.809389  0.123222  0.135600
3       AK  2021      1     4  0.107258  0.828516  0.064161 -0.040829
4       AK  2021      1    53  0.129545  0.785182  0.085273  0.052718
...    ...   ...    ...   ...       ...       ...       ...       ...
5642    WY  2022     10    40  0.192000  0.808000  0.000000 -0.638600
5643    WY  2022     10    41  0.320000  0.680000  0.000000 -0.840000
5644    WY  2022     10    42  0.273000  0.455000  0.273000  0.000000
5645    WY  2022     10    43  0.098000  0.787000  0.115000  0.168833
5646    WY  2022     11    46  0.041000  0.871500  0.087500  0.180600

         Happy     Angry  Surprise       Sad      Fear  \
0     0.113684  0.052632  0.074211  0.210526  0.074737
1     0.052813  0.009687  0.079687  0.079063  0.403125
2     0.138889  0.091111  0.220556  0.108333  0.217778
3     0.139032  0.075161  0.053226  0.146774  0.263226
4     0.000000  0.033636  0.170000  0.151818  0.463636
...        ...       ...       ...       ...       ...
5642  0.000000  0.000000  0.250000  0.500000  0.250000
5643  0.000000  0.500000  0.500000  0.000000  0.000000
5644  0.000000  0.000000  1.000000  0.000000  0.000000
5645  0.000000  0.110000  0.000000  0.000000  0.890000
5646  0.000000  0.000000  0.000000  1.000000  0.000000

      Administered_Dose1_Pop_Pct  Series_Complete_Pop_Pct  \
0                            0.0                      0.0
1                            0.0                      0.0
2                            0.0                      0.0
3                            0.0                      0.0
4                            0.0                      0.0
...                          ...                      ...
5642                        59.6                     52.2
5643                        59.7                     52.2
5644                        59.8                     52.3
5645                        59.9                     52.4
5646                        60.4                     52.7

      Additional_Doses_Vax_Pct
0                          0.0
1                          0.0
2                          0.0
3                          0.0
4                          0.0
...                        ...
5642                      45.6
5643                      45.7
5644                      45.9
5645                      46.1
5646                      46.5

[5647 rows x 16 columns]

In [259]:
#v5 start
#finding 5 most liked messages every month by state
df_v3_path = os.path.join(directory, 'data_with_sentiment_and_emotion.csv')
data = pd.read_csv(df_v3_path)
data2 = data.loc[data['loc_type'] == 'city']

In [260]:
data3 = data2[['state', 'Year', 'Month', 'text', 'loc_name', 'likes_count']].reset_index()
data4 = data3.groupby(['state', 'Year', 'Month'])['likes_count'].nlargest(5).reset_index()
print(data4['level_3'])
final_data = data3.iloc[data4['level_3']]
print(final_data)
path = os.path.join(directory, 'high_like_tweets.csv')
final_data.to_csv(path, index=False)
#v5 end

0       391637
1        14414
2        25526
3       383557
4        30674
         ...
5962    421530
5963    418229
5964    420961
5965    421644
5966    424278
Name: level_3, Length: 5967, dtype: int64
         index state  Year  Month  \
391637  464606    AK  2021      1
14414    17145    AK  2021      1
25526    30178    AK  2021      1
383557  455008    AK  2021      1
30674    36223    AK  2021      1
...        ...   ...   ...    ...
421530  500382    WY  2022     10
418229  496418    WY  2022     10
420961  499706    WY  2022     10
421644  500514    WY  2022     10
424278  503723    WY  2022     11

                                                     text  \
391637  I wish I could wipe away the pain this has cau...
14414   The most Alaska of vaccine stories.... https:/...
25526   Here‚Äôs a photo from the observation room after...
383557  Please protect yourself from these predators, ...
30674   Truly a weather legend and a sad loss today. h...
...                                                   ...
421530  Everyone knows the CORONAVIRUS came from the W...
418229  @RealCalvin1 If the vaccine had little to no e...
420961  Funniest shit this mf has ever done üòÇ https://...
421644  @Thewiseonewon @townhallcom I am also done wit...
424278  How does this even make sense‚Ä¶ https://t.co/Wo...

                     loc_name  likes_count
391637              Anchorage          582
14414               Anchorage           33
25526               Anchorage            7
383557              Anchorage            7
30674               Anchorage            6
...                       ...          ...
421530                Worland            9
418229                Worland            1
420961               Cheyenne            0
421644                Worland            0
424278  Warren Air Force Base            0

[5967 rows x 7 columns]

In [266]:
#v6 start
#calculating pearson coefficient for sentiment and emotion for each state
path = os.path.join(directory, 'weekly_vax_sentiment_emotion.csv')
df = pd.read_csv(path)
axis1 = ['neg', 'neu', 'pos', 'compound', 'Happy', 'Angry', 'Surprise', 'Sad', 'Fear']
df.rename(columns={'Administered_Dose1_Pop_Pct':'Dose1', 'Series_Complete_Pop_Pct':'Dose2', 'Additional_Doses_Vax_Pct':'Dose3'}, inplace=True)
print(df)
axis2 = ['Dose1', 'Dose2', 'Dose3']

     state  Year  Month  Week       neg       neu       pos  compound  \
0       AK  2021      1     1  0.080263  0.872000  0.047737 -0.049653
1       AK  2021      1     2  0.070125  0.855656  0.074187  0.025209
2       AK  2021      1     3  0.067444  0.809389  0.123222  0.135600
3       AK  2021      1     4  0.107258  0.828516  0.064161 -0.040829
4       AK  2021      1    53  0.129545  0.785182  0.085273  0.052718
...    ...   ...    ...   ...       ...       ...       ...       ...
5642    WY  2022     10    40  0.192000  0.808000  0.000000 -0.638600
5643    WY  2022     10    41  0.320000  0.680000  0.000000 -0.840000
5644    WY  2022     10    42  0.273000  0.455000  0.273000  0.000000
5645    WY  2022     10    43  0.098000  0.787000  0.115000  0.168833
5646    WY  2022     11    46  0.041000  0.871500  0.087500  0.180600

         Happy     Angry  Surprise       Sad      Fear  Dose1  Dose2  Dose3
0     0.113684  0.052632  0.074211  0.210526  0.074737    0.0    0.0    0.0
1     0.052813  0.009687  0.079687  0.079063  0.403125    0.0    0.0    0.0
2     0.138889  0.091111  0.220556  0.108333  0.217778    0.0    0.0    0.0
3     0.139032  0.075161  0.053226  0.146774  0.263226    0.0    0.0    0.0
4     0.000000  0.033636  0.170000  0.151818  0.463636    0.0    0.0    0.0
...        ...       ...       ...       ...       ...    ...    ...    ...
5642  0.000000  0.000000  0.250000  0.500000  0.250000   59.6   52.2   45.6
5643  0.000000  0.500000  0.500000  0.000000  0.000000   59.7   52.2   45.7
5644  0.000000  0.000000  1.000000  0.000000  0.000000   59.8   52.3   45.9
5645  0.000000  0.110000  0.000000  0.000000  0.890000   59.9   52.4   46.1
5646  0.000000  0.000000  0.000000  1.000000  0.000000   60.4   52.7   46.5

[5647 rows x 16 columns]

In [267]:
state_averages_df = df.groupby(['state']).mean().reset_index()
test = df.iloc[5550]
print((test['Angry'] - state_averages_df[state_averages_df['state'] == test['state']]['Angry']).iloc[0])
test['test'] = (test['Angry'] - state_averages_df[state_averages_df['state'] == test['state']]['Angry'].iloc[0])
print(test)
for a1 in axis1:
    df['avg'+a1] = df.apply(lambda x: (state_averages_df[state_averages_df['state'] == x['state']][a1]).iloc[0], axis=1)
for a2 in axis2:
    df['avg'+a2] = df.apply(lambda x: (state_averages_df[state_averages_df['state'] == x['state']][a2]).iloc[0], axis=1)
print(df)

-0.04190428615595686
state              WV
Year             2022
Month               8
Week               32
neg             0.227
neu             0.649
pos             0.124
compound      -0.4389
Happy               0
Angry               0
Surprise            0
Sad              0.67
Fear             0.33
Dose1            66.1
Dose2            58.5
Dose3            47.6
test       -0.0419043
Name: 5550, dtype: object

E:\miniconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
E:\miniconda3\envs\py37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

     state  Year  Month  Week       neg       neu       pos  compound  \
0       AK  2021      1     1  0.080263  0.872000  0.047737 -0.049653
1       AK  2021      1     2  0.070125  0.855656  0.074187  0.025209
2       AK  2021      1     3  0.067444  0.809389  0.123222  0.135600
3       AK  2021      1     4  0.107258  0.828516  0.064161 -0.040829
4       AK  2021      1    53  0.129545  0.785182  0.085273  0.052718
...    ...   ...    ...   ...       ...       ...       ...       ...
5642    WY  2022     10    40  0.192000  0.808000  0.000000 -0.638600
5643    WY  2022     10    41  0.320000  0.680000  0.000000 -0.840000
5644    WY  2022     10    42  0.273000  0.455000  0.273000  0.000000
5645    WY  2022     10    43  0.098000  0.787000  0.115000  0.168833
5646    WY  2022     11    46  0.041000  0.871500  0.087500  0.180600

         Happy     Angry  ...    avgpos  avgcompound  avgHappy  avgAngry  \
0     0.113684  0.052632  ...  0.096902     0.050994  0.118944  0.038789
1     0.052813  0.009687  ...  0.096902     0.050994  0.118944  0.038789
2     0.138889  0.091111  ...  0.096902     0.050994  0.118944  0.038789
3     0.139032  0.075161  ...  0.096902     0.050994  0.118944  0.038789
4     0.000000  0.033636  ...  0.096902     0.050994  0.118944  0.038789
...        ...       ...  ...       ...          ...       ...       ...
5642  0.000000  0.000000  ...  0.099448     0.006128  0.079812  0.041475
5643  0.000000  0.500000  ...  0.099448     0.006128  0.079812  0.041475
5644  0.000000  0.000000  ...  0.099448     0.006128  0.079812  0.041475
5645  0.000000  0.110000  ...  0.099448     0.006128  0.079812  0.041475
5646  0.000000  0.000000  ...  0.099448     0.006128  0.079812  0.041475

      avgSurprise    avgSad   avgFear   avgDose1   avgDose2   avgDose3
0        0.103027  0.158036  0.235400  53.977086  46.505481  20.310007
1        0.103027  0.158036  0.235400  53.977086  46.505481  20.310007
2        0.103027  0.158036  0.235400  53.977086  46.505481  20.310007
3        0.103027  0.158036  0.235400  53.977086  46.505481  20.310007
4        0.103027  0.158036  0.235400  53.977086  46.505481  20.310007
...           ...       ...       ...        ...        ...        ...
5642     0.131429  0.183188  0.290745  43.080177  36.365337  17.716556
5643     0.131429  0.183188  0.290745  43.080177  36.365337  17.716556
5644     0.131429  0.183188  0.290745  43.080177  36.365337  17.716556
5645     0.131429  0.183188  0.290745  43.080177  36.365337  17.716556
5646     0.131429  0.183188  0.290745  43.080177  36.365337  17.716556

[5647 rows x 28 columns]

In [268]:
for a1 in axis1:
    df['x'+a1] = df.apply(lambda x: x[a1] - x['avg'+a1], axis=1)
for a2 in axis2:
    df['y'+a2] = df.apply(lambda x: x[a2] - x['avg'+a2], axis=1)
for a1 in axis1:
    df['x2'+a1] = df.apply(lambda x: x['x'+a1]**2, axis=1)
for a2 in axis2:
    df['y2'+a2] = df.apply(lambda x: x['y'+a2]**2, axis=1)
for a1 in axis1:
    for a2 in axis2:
        df['xy'+a1+a2] = df.apply(lambda x: x['x'+a1] * x['y'+a2], axis=1)
# print(df)

In [269]:
r_df = df.groupby('state').sum()
rs = []
for a1 in axis1:
    for a2 in axis2:
        rs.append('r'+a1+a2)
        r_df['r'+a1+a2] = r_df.apply(lambda x: x['xy'+a1+a2]/np.sqrt(x['x2'+a1]*x['y2'+a2]), axis=1)
r_df = r_df[rs]

E:\miniconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in double_scalars

In [271]:
r_path = os.path.join(directory, 'r_by_state.csv')
r_df.to_csv(r_path, index=False)
#v6 end

In [5]:
r_path = os.path.join(directory, 'r_by_state.csv')
df = pd.read_csv(r_path)
df = df.mean()
print(df)

rnegDose1         0.014237
rnegDose2         0.028950
rnegDose3         0.003586
rneuDose1         0.070327
rneuDose2         0.060729
rneuDose3         0.060570
rposDose1        -0.098498
rposDose2        -0.100877
rposDose3        -0.101019
rcompoundDose1   -0.095518
rcompoundDose2   -0.109095
rcompoundDose3   -0.072484
rHappyDose1      -0.067132
rHappyDose2      -0.072087
rHappyDose3      -0.070904
rAngryDose1       0.012397
rAngryDose2       0.012571
rAngryDose3       0.035822
rSurpriseDose1   -0.043897
rSurpriseDose2   -0.048422
rSurpriseDose3   -0.001563
rSadDose1         0.059292
rSadDose2         0.062360
rSadDose3         0.064094
rFearDose1        0.071491
rFearDose2        0.072517
rFearDose3        0.071221
dtype: float64